
package vista;

import conexion.ConexionMySQL;
import java.sql.Connection;

public class ProductosRecepcion extends javax.swing.JInternalFrame {

    ConexionMySQL con = new ConexionMySQL();
    Connection cn = con.getConnection();
    
    public ProductosRecepcion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRecepcion = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        txtTipoMov = new javax.swing.JTextField();
        lblTipoMov = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        lblMotivo = new javax.swing.JLabel();
        txtCodProducto = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblFechaVenc = new javax.swing.JLabel();
        lblCodProducto = new javax.swing.JLabel();
        txtMotivo = new javax.swing.JTextField();
        lblVigente = new javax.swing.JLabel();
        txtVigente = new javax.swing.JTextField();
        ftfFechaVenc = new javax.swing.JFormattedTextField();

        lblRecepcion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblRecepcion.setText("RECEPCIÓN:");

        lblCantidad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCantidad.setText("Cantidad:");

        txtTipoMov.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblTipoMov.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTipoMov.setText("Tipo movimiento:");

        txtCantidad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblMotivo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMotivo.setText("Motivo:");

        txtCodProducto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnGuardar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblFechaVenc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblFechaVenc.setText("Fecha vencimiento:");

        lblCodProducto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCodProducto.setText("Código producto:");

        txtMotivo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblVigente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblVigente.setText("Vigente:");

        txtVigente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        ftfFechaVenc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRecepcion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(btnCancelar))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblVigente)
                    .addComponent(lblFechaVenc)
                    .addComponent(lblCodProducto)
                    .addComponent(lblCantidad)
                    .addComponent(lblTipoMov)
                    .addComponent(lblMotivo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMotivo)
                    .addComponent(txtTipoMov)
                    .addComponent(txtCantidad)
                    .addComponent(txtCodProducto)
                    .addComponent(txtVigente)
                    .addComponent(ftfFechaVenc)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRecepcion)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodProducto)
                    .addComponent(txtCodProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantidad)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoMov)
                    .addComponent(txtTipoMov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMotivo)
                    .addComponent(txtMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFechaVenc)
                    .addComponent(ftfFechaVenc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVigente)
                    .addComponent(txtVigente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        
    }//GEN-LAST:event_btnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JFormattedTextField ftfFechaVenc;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblCodProducto;
    private javax.swing.JLabel lblFechaVenc;
    private javax.swing.JLabel lblMotivo;
    private javax.swing.JLabel lblRecepcion;
    private javax.swing.JLabel lblTipoMov;
    private javax.swing.JLabel lblVigente;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodProducto;
    private javax.swing.JTextField txtMotivo;
    private javax.swing.JTextField txtTipoMov;
    private javax.swing.JTextField txtVigente;
    // End of variables declaration//GEN-END:variables
}
